# Generated by Django 5.2.5 on 2025-08-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
    ]
