# Generated by Django 5.2.5 on 2025-08-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
