# Generated by Django 5.2.5 on 2025-09-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mcq_pdfupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
