# Generated by Django 5.2.5 on 2025-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pdfupload_approved_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
