# Generated by Django 5.2.5 on 2025-09-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_quizattempt_correct_answers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_questions', models.PositiveIntegerField(default=10)),
                ('preferred_difficulty', models.CharField(blank=True, max_length=10)),
                ('enable_timer', models.BooleanField(default=True)),
                ('show_answers', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_quiz', 'First Quiz'), ('hot_streak', 'Hot Streak'), ('scholar', 'Scholar'), ('quiz_master', 'Quiz Master'), ('consistent', 'Consistent'), ('speed_demon', 'Speed Demon')], max_length=20)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
