# Generated by Django 5.2.5 on 2025-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_quizattempt_difficulty_quizattempt_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
