# Generated by Django 5.2.5 on 2025-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_quizattempt_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
