# Generated by Django 5.2.6 on 2025-09-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_generatedmcq'),
        ('base', '0012_alter_quizattempt_time_taken'),
    ]

    operations = [
    ]
