# Generated by Django 5.2.6 on 2025-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20250926_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.FloatField(default=0.0),
        ),
    ]
